/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_test_JNITest */

#ifndef _Included_jni_test_JNITest
#define _Included_jni_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_test_JNITest
 * Method:    doSomething
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_test_JNITest_doSomething
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jni_test_JNITest
 * Method:    doSomethingWithLists
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_test_JNITest_doSomethingWithLists
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     jni_test_JNITest
 * Method:    doSomethingWithPsm
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_test_JNITest_doSomethingWithPsm
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
