/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgr_jni_test_JNITest */

#ifndef _Included_cgr_jni_test_JNITest
#define _Included_cgr_jni_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgr_jni_test_JNITest
 * Method:    doSomething
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cgr_1jni_test_JNITest_doSomething
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cgr_jni_test_JNITest
 * Method:    doSomethingWithLists
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cgr_1jni_test_JNITest_doSomethingWithLists
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     cgr_jni_test_JNITest
 * Method:    doSomethingWithPsm
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cgr_1jni_test_JNITest_doSomethingWithPsm
  (JNIEnv *, jclass, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
